version: '2'
services:
    authapplication-app:
        image: authapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://authapplication-mysql:3306/authapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    authapplication-mysql:
        extends:
            file: mysql.yml
            service: authapplication-mysql
